/**
 * Array of all available fiat currency codes.
 * @todo Define display name for each currency in i18n.
 */
const fiat = [
  'jpy', // Japanese Yen, which will be used
  'usd', // US Dollar, which will be used
  'eur', // Euro, which is generated by GitHub Copilot and won't be used
  'gbp', // British Pound, which is generated by GitHub Copilot and won't be used
  'cad', // Canadian Dollar, which is generated by GitHub Copilot and won't be used
  'aud', // Australian Dollar, which is generated by GitHub Copilot and won't be used
  'nzd', // New Zealand Dollar, which is generated by GitHub Copilot and won't be used
  'chf', // Swiss Franc, which is generated by GitHub Copilot and won't be used
] as const;
/**
 * Type of fiat currency code.
 */
export type Fiat = (typeof fiat)[number];

/**
 * Array of the BTC expression type
 * @todo Define display name for each currency in i18n: If you support other cryptos, you only need to rewrite the name in i18n.
 */
const crypto = [
  'btc', // Bitcoin, which will be used
  'sat', // Satoshis, which will be used
] as const;
/**
 * Type of crypto currency code.
 */
export type Crypto = (typeof crypto)[number];
/**
 * Type of all currency code.
 */
export type CurrencyUnit = Fiat | Crypto;
