name: AndroidLint
on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Install deps
        run: npm ci
      - name: lint Android
        run: cd android && ./gradlew lintNmainRelease
